language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"
		
env:
    - PLATFORMIO_CI_SRC=onboard-software/tubular-platformIO/test
	
install:
    # Install PlatformIO
    - pip install -U platformio
	
before_script:
    # Run tests
    - platformio test -e native
	
script:
    # Check that the example builds
    - platformio ci --lib="." --board=due --project-option="build_flags=-Werror"